import type { SpanData } from "@assistant-ui/react-o11y";

const BASE = Date.now() - 5000;

export const mockSpans: SpanData[] = [
  {
    id: "span-1",
    parentSpanId: null,
    name: "POST /api/chat",
    type: "api",
    status: "completed",
    startedAt: BASE,
    endedAt: BASE + 4200,
    latencyMs: 4200,
  },
  {
    id: "span-2",
    parentSpanId: "span-1",
    name: "authenticate",
    type: "action",
    status: "completed",
    startedAt: BASE + 50,
    endedAt: BASE + 200,
    latencyMs: 150,
  },
  {
    id: "span-3",
    parentSpanId: "span-1",
    name: "agent-pipeline",
    type: "pipeline",
    status: "completed",
    startedAt: BASE + 220,
    endedAt: BASE + 4100,
    latencyMs: 3880,
  },
  {
    id: "span-4",
    parentSpanId: "span-3",
    name: "retrieve-context",
    type: "tool",
    status: "completed",
    startedAt: BASE + 250,
    endedAt: BASE + 900,
    latencyMs: 650,
  },
  {
    id: "span-5",
    parentSpanId: "span-3",
    name: "llm-generate",
    type: "action",
    status: "completed",
    startedAt: BASE + 920,
    endedAt: BASE + 2800,
    latencyMs: 1880,
  },
  {
    id: "span-6",
    parentSpanId: "span-3",
    name: "web-search",
    type: "tool",
    status: "completed",
    startedAt: BASE + 2850,
    endedAt: BASE + 3500,
    latencyMs: 650,
  },
  {
    id: "span-7",
    parentSpanId: "span-3",
    name: "llm-summarize",
    type: "action",
    status: "completed",
    startedAt: BASE + 3520,
    endedAt: BASE + 4050,
    latencyMs: 530,
  },
  {
    id: "span-8",
    parentSpanId: "span-1",
    name: "log-response",
    type: "action",
    status: "completed",
    startedAt: BASE + 4110,
    endedAt: BASE + 4180,
    latencyMs: 70,
  },
  {
    id: "span-9",
    parentSpanId: null,
    name: "POST /api/feedback",
    type: "api",
    status: "completed",
    startedAt: BASE + 4500,
    endedAt: BASE + 4700,
    latencyMs: 200,
  },
  {
    id: "span-10",
    parentSpanId: "span-9",
    name: "validate-input",
    type: "action",
    status: "completed",
    startedAt: BASE + 4520,
    endedAt: BASE + 4560,
    latencyMs: 40,
  },
  {
    id: "span-11",
    parentSpanId: "span-9",
    name: "store-feedback",
    type: "action",
    status: "failed",
    startedAt: BASE + 4570,
    endedAt: BASE + 4680,
    latencyMs: 110,
  },
  {
    id: "span-12",
    parentSpanId: null,
    name: "GET /api/status",
    type: "api",
    status: "running",
    startedAt: BASE + 4800,
    endedAt: null,
    latencyMs: null,
  },
  {
    id: "span-13",
    parentSpanId: "span-12",
    name: "health-check",
    type: "flow",
    status: "running",
    startedAt: BASE + 4830,
    endedAt: null,
    latencyMs: null,
  },
  {
    id: "span-14",
    parentSpanId: "span-4",
    name: "vector-search",
    type: "tool",
    status: "completed",
    startedAt: BASE + 280,
    endedAt: BASE + 700,
    latencyMs: 420,
  },
  {
    id: "span-15",
    parentSpanId: "span-4",
    name: "rerank",
    type: "action",
    status: "completed",
    startedAt: BASE + 710,
    endedAt: BASE + 880,
    latencyMs: 170,
  },
];
