/**
 * The installable elements, as [slug, title, registry item, runtime-wired].
 * A data-only mirror of components/pages/elements/registry.tsx: the cart runs
 * in the site header, so it cannot import the registry and its demos.
 * element-index.test.ts fails when the two drift.
 */
export const ELEMENT_INDEX: readonly (readonly [
  slug: string,
  title: string,
  registryItem: string,
  runtimeWired: boolean,
])[] = [
  ["loading-state", "Loader", "elements-loading-state", false],
  [
    "thinking-indicator",
    "Thinking indicator",
    "elements-thinking-indicator",
    false,
  ],
  ["streaming-text", "Streaming text", "elements-streaming-text", false],
  ["typing-indicator", "Typing indicator", "elements-typing-indicator", false],
  ["reasoning-effort", "Reasoning effort", "elements-reasoning-effort", false],
  ["guardrail-notice", "Guardrail notice", "elements-guardrail-notice", false],
  ["message-pair", "Message pair", "elements-message-pair", false],
  ["message-branches", "Message branches", "elements-message-branches", false],
  ["message-actions", "Message actions", "elements-message-actions", false],
  ["error-state", "Error state", "elements-error-state", false],
  ["message-queue", "Message queue", "elements-message-queue", false],
  ["edit-message", "Edit a sent message", "elements-edit-message", false],
  ["feedback-dialog", "Feedback dialog", "elements-feedback-dialog", false],
  ["stopped-run", "Stopped run", "elements-stopped-run", false],
  ["day-separator", "Timestamps", "elements-day-separator", false],
  ["speaker-identity", "Speaker identity", "elements-speaker-identity", false],
  ["regenerate-menu", "Regenerate with", "elements-regenerate-menu", false],
  ["confidence-marker", "Confidence", "elements-confidence-marker", false],
  ["tool-call", "Tool call", "elements-tool-call", false],
  ["tool-timeline", "Tool timeline", "elements-tool-timeline", false],
  ["terminal-block", "Terminal block", "elements-terminal-block", false],
  ["code-diff", "Code diff", "elements-code-diff", false],
  ["reviewable-diff", "Reviewable diff", "elements-reviewable-diff", false],
  ["file-tree", "File tree", "elements-file-tree", false],
  ["elicitation-form", "Elicitation form", "elements-elicitation-form", false],
  ["mcp-server-panel", "Server panel", "elements-mcp-server-panel", false],
  ["tool-error", "Tool failure", "elements-tool-error", false],
  ["permission-grant", "Permission grant", "elements-permission-grant", false],
  ["computer-use", "Computer use", "elements-computer-use", false],
  ["code-runner", "Code runner", "elements-code-runner", false],
  ["web-search", "Web search", "elements-web-search", false],
  ["inline-citation", "Inline citation", "elements-inline-citation", false],
  ["image-generation", "Image generation", "elements-image-generation", false],
  ["retrieval-chunks", "Retrieval chunks", "elements-retrieval-chunks", false],
  [
    "document-reference",
    "Document reference",
    "elements-document-reference",
    false,
  ],
  ["memory-chips", "Memory", "elements-memory-chips", false],
  ["research-report", "Research report", "elements-research-report", false],
  ["map-answer", "Map", "elements-map-answer", false],
  ["data-table", "Data table", "elements-data-table", false],
  ["number-ticker", "Number ticker", "elements-number-ticker", false],
  ["chart", "Chart", "elements-chart", false],
  ["web-preview", "Web preview", "elements-web-preview", false],
  ["diagram", "Diagram", "elements-diagram", false],
  ["flow-graph", "Flow graph", "elements-flow-graph", false],
  ["activity-graph", "Activity graph", "elements-activity-graph", false],
  ["math-block", "Math", "elements-math-block", false],
  ["spec-sheet", "Spec sheet", "elements-spec-sheet", false],
  ["comparison-card", "Comparison", "elements-comparison-card", false],
  ["timeline", "Timeline", "elements-timeline", false],
  ["job-progress", "Job progress", "elements-job-progress", false],
  ["score-breakdown", "Score breakdown", "elements-score-breakdown", false],
  ["agent-plan", "Agent plan", "elements-agent-plan", false],
  ["subagent-list", "Subagent list", "elements-subagent-list", false],
  ["task-card", "Task card", "task-card", true],
  ["agent-status", "Agent status", "agent-status", true],
  ["approval-card", "Approval card", "elements-approval-card", false],
  [
    "recommendation-card",
    "Recommendation card",
    "elements-recommendation-card",
    false,
  ],
  ["artifact-card", "Artifact card", "elements-artifact-card", false],
  ["todo-list", "Todo list", "elements-todo-list", false],
  ["agent-card", "Agent card", "elements-agent-card", false],
  ["agent-handoff", "Handoff", "elements-agent-handoff", false],
  ["background-inbox", "Background runs", "elements-background-inbox", false],
  ["checkpoint-history", "Checkpoints", "elements-checkpoint-history", false],
  ["schedule-card", "Schedule", "elements-schedule-card", false],
  ["trace-waterfall", "Trace waterfall", "elements-trace-waterfall", false],
  ["cost-meter", "Cost meter", "elements-cost-meter", false],
  ["quota-banner", "Quota banner", "elements-quota-banner", false],
  ["composer", "Composer", "elements-composer", false],
  ["composer-slash-commands", "Slash commands", "elements-composer", false],
  ["composer-mentions", "Mentions", "elements-composer", false],
  ["composer-attachments", "Attachments", "elements-composer", false],
  ["composer-model-picker", "Models", "elements-composer", false],
  ["composer-voice", "Dictation", "elements-composer", false],
  ["composer-context", "Context", "elements-composer", false],
  ["draft-restore", "Draft restore", "elements-draft-restore", false],
  [
    "context-breakdown",
    "Context breakdown",
    "elements-context-breakdown",
    false,
  ],
  ["prompt-library", "Prompt library", "elements-prompt-library", false],
  ["command-palette", "Command palette", "elements-command-palette", false],
  ["voice-conversation", "Voice conversation", "voice-conversation", true],
  ["read-aloud", "Read aloud", "elements-read-aloud", false],
  ["chat-panel", "Chat panel", "elements-chat-panel", false],
  ["empty-state", "Empty state", "elements-empty-state", false],
  ["scroll-anchor", "Scroll anchor", "elements-scroll-anchor", false],
  ["canvas-split", "Canvas", "elements-canvas-split", false],
  ["connection-state", "Connection state", "elements-connection-state", false],
  [
    "shared-conversation",
    "Shared conversation",
    "elements-shared-conversation",
    false,
  ],
  [
    "conversation-search",
    "Search in conversation",
    "elements-conversation-search",
    false,
  ],
  ["thread-search", "Thread search", "elements-thread-search", false],
  ["launcher-bubble", "Launcher", "elements-launcher-bubble", false],
  ["settings-panel", "Settings", "elements-settings-panel", false],
  ["onboarding", "Onboarding", "elements-onboarding", false],
  ["mobile-composer", "Mobile composer", "elements-mobile-composer", false],
  ["thread", "Thread", "thread", true],
  ["assistant-modal", "Assistant modal", "assistant-modal", true],
  ["assistant-sidebar", "Assistant sidebar", "assistant-sidebar", true],
  ["thread-list", "Thread list", "thread-list", true],
  ["thread-list-sidebar", "Thread list sidebar", "threadlist-sidebar", true],
  ["orb", "Orb", "voice", true],
  ["reasoning", "Reasoning", "reasoning", true],
  ["message-timing", "Message timing", "message-timing", true],
  ["context-display", "Context display", "context-display", true],
  ["mcp-config", "MCP config dialog", "mcp-config", true],
  ["attachment", "Attachment", "attachment", true],
  [
    "follow-up-suggestions",
    "Follow-up suggestions",
    "follow-up-suggestions",
    true,
  ],
  ["tool-fallback", "Tool fallback", "tool-fallback", true],
  ["tool-group", "Tool group", "tool-group", true],
  ["quote", "Quote", "quote", true],
  ["sources", "Sources", "sources", true],
  ["image", "Image", "image", true],
  ["file", "File", "file", true],
  ["model-selector", "Model selector", "model-selector", true],
  [
    "composer-trigger-popover",
    "Composer trigger popover",
    "composer-trigger-popover",
    true,
  ],
  ["directive-text", "Directive text", "directive-text", true],
  ["markdown-text", "Markdown text", "markdown-text", true],
  ["syntax-highlighter", "Syntax highlighter", "syntax-highlighter", false],
  ["shiki-highlighter", "Shiki highlighter", "shiki-highlighter", true],
  ["mermaid-diagram", "Mermaid diagram", "mermaid-diagram", false],
  ["generative-ui", "Generative UI", "generative-ui", false],
  ["tooltip-icon-button", "Tooltip icon button", "tooltip-icon-button", false],
  ["logos", "Model logos", "logos", false],
  ["heat-graph", "Heat graph", "heat-graph", false],
];
